---
title: "interactive"
author: "Ross Hemmel (rhemmel)"
date: "4/30/2018"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE, message=FALSE}
library(shiny)
library(tidyverse)
library(plotly)
```

```{r, message = FALSE}
census <- read_csv("adult_census_income.csv") %>% 
  select(-fnlwgt) %>% 
  mutate(occupation = ifelse(occupation == "?", "Unknown", occupation) %>% 
           factor,
         workclass =  ifelse(workclass == "?", "Unknown", workclass) %>% 
           factor,
         education = education %>% factor, 
         marital.status = marital.status %>% factor,
         relationship = relationship %>% factor,
         race = race %>% factor,
         sex = sex %>% factor,
         native.country = native.country %>% factor,
         income = income %>% factor,
         capital.income = ifelse(capital.gain > 0, capital.gain, -capital.loss),
         us_born = ifelse(native.country == "United-States", "US Born", "Not US Born"))


# Define UI 
ui <- fluidPage(

  # App title 
  titlePanel("Careers, Work Sector, and Income"),

  # Sidebar layout with input and output definitions ----
  sidebarLayout(

    # Sidebar panel for inputs ----
    sidebarPanel(

      # Input
      selectInput(inputId = "occupation",
                  label = "Select an Occupation",
                  choices = c("All" = "all",
                              "Administrative/Clerical" = "Adm-clerical", 
                              "Armed Forces" = "Armed-Forces", 
                              "Craft/Repair" = "Craft-repair",
                              "Executive/Managerial" = "Exec-managerial",
                              "Farming/Fishing" = "Farming-fishing",
                              "Handlers/Cleaners" = "Handlers-cleaners",
                              "Machine Operators/Inspectors" = 
                                "Machine-op-inspct",
                              "Other Services" = "Other-service",
                              "Private House Service" = "Priv-house-serv",
                              "Professional/Specialty" = "Prof-specialty",
                              "Protective Service" = "Protective-serv",
                              "Sales" = "Sales",
                              "Tech Support" = "Tech-support",
                              "Transport/Moving" = "Transport-moving",
                              "Unknown" = "Unknown")),
      radioButtons("workclass", label = "Select a Work Sector",
                   choices = c("All" = "all",
                              "Federal Government" = "Federal-gov",
                              "Local Government" = "Local-gov",
                              "Never Worked" = "Never-worked",
                              "Private" = "Private",
                              "Self Employed (incorporated)" = "Self-emp-inc",
                              "Self Employed (not incorporated)" = 
                                "Self-emp-not-inc",
                              "State Government" = "State-gov",
                              "Unknown" = "Unknown",
                              "Without Pay" = "Without-pay")
      ),
      checkboxInput("inc0", label = "Include 0 Capital Income?"),
      checkboxInput("inc99999", label = "Include Capital Income > $99,999?"),
      checkboxInput("prop_hist", label = "Proportional Histogram?"),
      radioButtons("facet", label = "Facet?",
                   choices = c("None" = "none",
                               "Sex" = "sex",
                               "Race" = "race",
                               "US Born" = "us_born"))

    ),

    # Main panel
    mainPanel(
      plotlyOutput("inc_plot"), plotOutput("cat_plot")
    )
  )
)

server <- function(input, output) {

  output$inc_plot <- renderPlotly({
    census_subset <- census
    if (!input$inc0) {
      census_subset <- census_subset %>% filter(capital.income != 0)
    }
    if (!input$inc99999) {
      census_subset <- census_subset %>% filter(capital.income != 99999)
    }
    if (input$occupation != "all") {
      census_subset <- census_subset %>% filter(occupation == input$occupation)
    }
    if (input$workclass != "all") {
      census_subset <- census_subset %>% filter(workclass == input$workclass)
    }
    
    ci_plot <- ggplot(data = census_subset, aes(x = capital.income, 
                                                fill = workclass)) +
      labs(title = "Distribution of Capital Income",
           subtitle = "The Intersection of Occupation and Work Sector",
           x = "Capital Income")
    if (input$prop_hist) {
      ci_plot <- ci_plot + 
        geom_histogram(binwidth = 1000, 
                       aes(y = ..count.. /
                             tapply(..count.., ..PANEL.., sum)[..PANEL..])) +
        labs(y = "Proportion")
    }
    else {
      ci_plot <- ci_plot + geom_histogram(binwidth = 1000) +
        labs(y = "Count")
    }
    if (input$workclass == "all"){
      ci_plot <- ci_plot + labs(fill = "Work Sector")
    }
    else{
      ci_plot <- ci_plot + guides(fill = FALSE)
    }
    if (input$facet == "sex") {
      ci_plot <- ci_plot + facet_grid(sex ~ .)
    }
    if (input$facet == "race") {
      ci_plot <- ci_plot + facet_wrap(~race)
    }
    if (input$facet == "us_born") {
      ci_plot <- ci_plot + facet_grid(us_born ~ .)
    }
    if (nrow(census_subset) == 0) {
      print("There are no observations satisfying the given criteria.")
    }
    else{
      ci_plot
    }
    })
  output$cat_plot <- renderPlot({
    census_subset <- census
    if (!input$inc0) {
      census_subset <- census_subset %>% filter(capital.income != 0)
    }
    if (!input$inc99999) {
      census_subset <- census_subset %>% filter(capital.income != 99999)
    }
    if (input$occupation != "all") {
      census_subset <- census_subset %>% filter(occupation == input$occupation)
    }
    if (input$workclass != "all") {
      census_subset <- census_subset %>% filter(workclass == input$workclass)
    }
    ct_p <- 
      ggplot(census_subset, aes(x = workclass, fill = income)) +
      geom_bar(position = "fill") +
      coord_flip() + 
      labs(title = "Relationship between Income Category and Work Sector",
           y = "Proportion",
           x = "Work Sector",
           fill = "Income")
    if (input$facet == "sex") {
      ct_p <- ct_p + facet_grid(sex ~ .)
    }
    if (input$facet == "race") {
      ct_p <- ct_p + facet_wrap(~race)
    }
    if (input$facet == "us_born") {
      ct_p <- ct_p + facet_grid(us_born ~ .)
    }
    ct_p

  })

}

shinyApp(ui = ui, server = server)
```